4. Django/Django/1. Django/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('dinner/', views.dinner, name='dinner'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('hello/<str:name>', views.hello, name='hello'),
    path('intro/<str:name>/<int:age>', views.intro, name='intro'),
]

4. Django/Django/1. Django/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

4. Django/Django/1. Django/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('index/', views.index, name='index')
]

4. Django/Django/1. Django/articles/models.py
from django.db import models

# Create your models here.

4. Django/Django/1. Django/pages/models.py
from django.db import models

# Create your models here.

4. Django/Django/1. Django/articles/views.py
from multiprocessing import context
from django.shortcuts import render
import random

# Create your views here.
def index(request):
    return render(request, 'index.html')

def greeting(request):
    foods = ['apple', 'banana', 'coconut']
    info = {
        'name': 'Alice'
    }
    context = {
        'foods' : foods,
        'info' : info,
    }
    return render(request, 'greeting.html', context)

def dinner(request):
    foods = ['족발', '햄버거', '치킨', '초밥']
    pick = random.choice(foods)
    context = {
        'foods': foods,
        'pick': pick,
    }
    return render(request, 'dinner.html', context)

def throw(request):
    return render(request, 'throw.html')

def catch(request):
    message = request.GET.get('message')
    context = {
        'message': message
    }
    return render(request, 'catch.html', context)

def hello(request, name):
    print(name, "##################")
    return render(request, 'hello.html', {'name': name})

def intro(request, name, age):
    context = {
        'name': name,
        'age': age,
    }
    return render(request, 'intro.html', context)

4. Django/Django/1. Django/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

4. Django/Django/1. Django/articles/templates/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>Catch</h1>
  <h2>여기서 {{ message }}를 받았습니다.</h2>
  <a href="{% url 'articles:throw' %}">다시 입력하기</a>
{% endblock content %}

4. Django/Django/1. Django/articles/templates/dinner.html
{% extends 'base.html' %}

{% block content %}
  <h1>오늘 저녁은 {{ pick }}이다!!</h1>
  <p>{{ pick }}은 {{ pick|length }}글자</p>
  <p>음식 목록은 {{ foods|join:", " }}</p>

  <p>메뉴판</p>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>

  {# 이것은 한 줄 주석입니다. #}

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}

4. Django/Django/1. Django/articles/templates/greeting.html
{% extends 'base.html' %}

{% block content %}
  <p>안녕하세요 저는 {{ info.name|lower }}입니다.</p>
  <p>제가 가장 좋아하는 음식은 {{ foods }}입니다.</p>
  <p>저는 사실 {{ foods.0 }}을 가장 좋아합니다.</p>

  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

4. Django/Django/1. Django/articles/templates/hello.html
{% extends 'base.html' %}

{% block content %}
<h1>hello! {{ name }}</h1>
{% endblock content %}

4. Django/Django/1. Django/articles/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>안녕하세요!</h1>

  <a href="{% url 'articles:dinner' %}">dinner</a><br>
  <a href="{% url 'articles:greeting' %}">greeting</a><br>
  <a href="{% url 'articles:throw' %}">throw</a><br>

  <a href="{% url 'pages:index' %}">Pages>index</a>
{% endblock content %}

4. Django/Django/1. Django/articles/templates/intro.html
{% extends 'base.html' %}

{% block content %}
  <h1>안녕하세요. {{ name }}님, 당신은 {{ age }}세 입니다.</h1>
{% endblock content %}

4. Django/Django/1. Django/articles/templates/throw.html
{% extends 'base.html' %}

{% block content %}
<h1>Throw</h1>

<form action="{% url 'articles:catch' %}">
  <label for="msg">메세지를 입력해주세요.</label>
  <input type="text" name="message" id="msg">
  <input type="submit">
</form>

{% endblock content %}

4. Django/Django/1. Django/pages/templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Pages App의 index.html</h1>
{% endblock content %}

4. Django/Django/1. Django/templates/_nav.html
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'articles:index' %}">Navbar</a>
</nav>

4. Django/Django/1. Django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
  {% include '_nav.html' %}

  {% block content %}
  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>