4. Django/Django/2. ORM/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name="new"),
    path('create/', views.create, name="create"),
    path('<int:pk>/', views.detail, name="detail"),
    path('<int:pk>/delete/', views.delete, name="delete"),
    path('<int:pk>/edit/', views.edit, name="edit"),
    path('<int:pk>/update/', views.update, name="update"),
]

4. Django/Django/2. ORM/crud_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
]

4. Django/Django/2. ORM/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

4. Django/Django/2. ORM/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    # 1. 모델을 이용해서 모든 데이터를 가져온다.
    #articles = Article.objects.all()[::-1]
    articles = Article.objects.order_by('-pk')
    # 2. 가져온 데이터를 템플릿으로 넘긴다.
    context = {'articles': articles}
    # 3. 템플릿에서 데이터를 보여준다.
    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')

    # DB에 데이터 저장하기
    article = Article(title = title, content = content)
    article.save()

    return redirect('articles:detail', article.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    if request.method == 'POST':
        # 1. pk에 해당하는 글을 DB에서 가져온다.
        article = Article.objects.get(pk=pk)
        # 2. 해당 글을 삭제한다.
        article.delete()
        # 3. index 페이지로 이동하게 한다.
        return redirect('articles:index')
    else:
        article = Article.objects.get(pk=pk)
        return redirect('articles:detail', article.pk)

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    # 1. 수정할 article을 가져온다.
    article = Article.objects.get(pk=pk)
    # 2. request로 부터 사용자가 입력한 데이터를 가져온다.
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    # 3. article을 수정한다.
    article.save()
    # 4. article 상세 페이지로 보낸다.
    return redirect('articles:detail', article.pk)

4. Django/Django/2. ORM/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">DETAIL</h1>

<h3>{{ article.id }}번째 글</h3>
<hr>
<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<p>작성 시각 : {{ article.created_at }}</p>
<p>수정 시각 : {{ article.updated_at }}</p>
<hr>
<a href="{% url 'articles:index' %}">목록보기</a>
<a href="{% url 'articles:edit' article.pk %}"" class="btn btn-primary">수정하기</a>

<form action="{% url 'articles:delete' article.pk %}" method="post">
  {% csrf_token %}
  <button class='btn btn-danger'>삭제하기</button>
</form>

{% endblock content %}

4. Django/Django/2. ORM/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">EDIT</h1>
  
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  <label for="title">Title :</label>
  <input type="text" name="title" id="title" value="{{ article.title }}"><br>
  <label for="content">Content :</label><br>
  <textarea name="content" id="content" cols="30" rows="5">{{ article.content }}</textarea><br>
  <input type="submit">
</form>

<a href="{% url 'articles:index' %}">목록보기</a>

{% endblock content %}

4. Django/Django/2. ORM/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">Articles</h1>
  <a href="{% url 'articles:new' %}">글쓰기</a><hr>

  {% for article in articles %}
  <p>글 번호 : {{ article.id }}</p>
  <a href="{% url 'articles:detail' article.id %}">글 제목 : {{ article.title }}</a>
  <hr>
  {% endfor %}
{% endblock content %}

4. Django/Django/2. ORM/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">New Article</h1>
  
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">Title :</label>
    <input type="text" name="title" id="title"><br>
    <label for="content">Content :</label><br>
    <textarea name="content" id="content" cols="30" rows="5"></textarea><br>
    <input type="submit">
  </form>

  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

4. Django/Django/2. ORM/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>

  {% block content %}
  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>