4. Django/django (Sign in&out)/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

4. Django/django (Sign in&out)/django_auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

4. Django/django (Sign in&out)/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

4. Django/django (Sign in&out)/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import CustomUserChangeForm

# Create your views here.
def index(request):
    return render(request, 'accounts/index.html')

def signup(request):
    if request.user.is_authenticated:   # 로그인된 유저가 회원가입 링크를 누르면 index페이지로 redirect
        return redirect('accounts:index')
    
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)   # 회원가입 후 자동 로그인 처리
            return redirect('accounts:index')
    else:
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.user.is_authenticated:   # 로그인된 유저가 로그인 링크를 누르면 index페이지로 redirect
        return redirect('accounts:index')

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()
    context = {'form': form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:index')

@require_POST
def delete(request):
    request.user.delete()
    return redirect('accounts:index')

def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/update.html', context)

def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('accounts:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form':form}
    return render(request, 'accounts/change_password.html', context)

# # UserCreationForm 사용하지 않고 작성 #
# def signup(request):
#     if request.method == "POST":
#         # 회원가입 진행
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         new_user = User.objects.create_user(
#             username = username,
#             password = password,
#         )
#         return redirect('accounts:index')
#     else:
#         # 비어있는 폼 보여주기
#         return render(request, 'accounts/signup.html')

# # AuthenticationForm 사용하지 않고 작성 #
# def login(request):
#     if request.method == "POST":
#         # 로그인 진행
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         # 아이디와 비밀번호 일치여부 확인
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             auth_login(request, user)
#             return redirect('accounts:index')
#         else:
#             error_message = "아이디 또는 비밀번호가 일치하지 않습니다."
#     else:
#         error_message = ""
#     context = {'error_message': error_message}
#     return render(request, 'accounts/login.html', context)

4. Django/django (Sign in&out)/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>비밀번호 변경</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type='submit'>변경하기</button>
  </form>
{% endblock content %}

4. Django/django (Sign in&out)/accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
  {% if user.is_authenticated %}
    <h3>안녕하세요, {{ user.username }}님!</h3>
    <a href="{% url 'accounts:update' %}">정보수정</a>
    <a href="{% url 'accounts:change_password' %}">비밀번호 변경</a>
    <a href="{% url 'accounts:logout' %}">로그아웃</a>
    <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline">
      {% csrf_token %}
      <input type="submit" value="회원탈퇴">
    </form>
  {% else %}
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    <a href="{% url 'accounts:login' %}">로그인</a>
  {% endif %}

  <h1>INDEX</h1>
{% endblock content %}

4. Django/django (Sign in&out)/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>로그인</h1>

  <form action="#" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}

    {% comment %}
    # UserCreationForm 사용하지 않고 작성 #
    <label for="username">유저네임:</label>
    <input type="text" id='username' name='username'>
    <br><br>
    <label for="password">비밀번호:</label>
    <input type="password" id='password' name='password'>
    <br><br>
    {% endcomment %}
    <button type='submit'>로그인</button>
  </form>
  <br><br>

  {% comment %}
  # UserCreationForm 사용하지 않고 작성 #
  {{ error_message }}
  {% endcomment %}

{% endblock content %}

4. Django/django (Sign in&out)/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>

  <form action="#" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}

    {% comment %}
    # UserCreationForm 사용하지 않고 작성 #
    <label for="username">유저네임:</label>
    <input type="text" id='username' name='username'>
    <br><br>
    <label for="password">비밀번호:</label>
    <input type="password" id='password' name='password'>
    <br><br>
    {% endcomment %}
    <button type='submit'>가입하기</button>
  </form>
{% endblock content %}

4. Django/django (Sign in&out)/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>정보수정</h1>

  <form action="#" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}

    <button type='submit'>수정하기</button>
  </form>
{% endblock content %}

4. Django/django (Sign in&out)/templates/base.html
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Auth</title>
</head>
<body>
  {% block content %}{% endblock content %}
</body>
</html>